// Language code to full name mapping
const LANGUAGE_NAMES = {
  'en': 'English',
  'es': 'Spanish',
  'fr': 'French',
  'de': 'German',
  'it': 'Italian',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'ar': 'Arabic',
  'hi': 'Hindi',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'pl': 'Polish',
  'nl': 'Dutch',
  'sv': 'Swedish',
  'da': 'Danish',
  'no': 'Norwegian',
  'fi': 'Finnish',
  'tr': 'Turkish',
  'he': 'Hebrew',
  'cs': 'Czech',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'bg': 'Bulgarian',
  'hr': 'Croatian',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'et': 'Estonian',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'uk': 'Ukrainian',
  'be': 'Belarusian',
  'mk': 'Macedonian',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'bs': 'Bosnian',
  'mt': 'Maltese',
  'is': 'Icelandic',
  'ga': 'Irish',
  'cy': 'Welsh',
  'eu': 'Basque',
  'ca': 'Catalan',
  'gl': 'Galician',
  'el': 'Greek',
  'ka': 'Georgian',
  'hy': 'Armenian',
  'az': 'Azerbaijani',
  'kk': 'Kazakh',
  'ky': 'Kyrgyz',
  'uz': 'Uzbek',
  'tg': 'Tajik',
  'mn': 'Mongolian',
  'my': 'Burmese',
  'km': 'Khmer',
  'lo': 'Lao',
  'si': 'Sinhala',
  'ta': 'Tamil',
  'te': 'Telugu',
  'ml': 'Malayalam',
  'kn': 'Kannada',
  'gu': 'Gujarati',
  'pa': 'Punjabi',
  'bn': 'Bengali',
  'or': 'Odia',
  'as': 'Assamese',
  'ne': 'Nepali',
  'ur': 'Urdu',
  'fa': 'Persian',
  'ps': 'Pashto',
  'sd': 'Sindhi',
  'ku': 'Kurdish',
  'sw': 'Swahili',
  'am': 'Amharic',
  'ti': 'Tigrinya',
  'om': 'Oromo',
  'so': 'Somali',
  'ha': 'Hausa',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'zu': 'Zulu',
  'xh': 'Xhosa',
  'af': 'Afrikaans',
  'id': 'Indonesian',
  'ms': 'Malay',
  'tl': 'Filipino',
  'ceb': 'Cebuano',
  'war': 'Waray',
  'ilo': 'Ilocano',
  'pam': 'Kapampangan',
  'bik': 'Bikol',
  'hil': 'Hiligaynon',
  'pag': 'Pangasinan',
  'mrw': 'Maranao',
  'mg': 'Malagasy',
  'rw': 'Kinyarwanda',
  'rn': 'Kirundi',
  'lg': 'Luganda',
  'ny': 'Chichewa',
  'sn': 'Shona',
  'st': 'Sesotho',
  'tn': 'Setswana',
  'ss': 'Swati',
  've': 'Venda',
  'ts': 'Tsonga',
  'nr': 'Ndebele',
  'nso': 'Northern Sotho'
};

// Country code to full name mapping
const COUNTRY_NAMES = {
  'US': 'United States',
  'GB': 'United Kingdom',
  'CA': 'Canada',
  'AU': 'Australia',
  'DE': 'Germany',
  'FR': 'France',
  'IT': 'Italy',
  'ES': 'Spain',
  'NL': 'Netherlands',
  'BE': 'Belgium',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'SE': 'Sweden',
  'NO': 'Norway',
  'DK': 'Denmark',
  'FI': 'Finland',
  'IS': 'Iceland',
  'IE': 'Ireland',
  'PT': 'Portugal',
  'GR': 'Greece',
  'CY': 'Cyprus',
  'MT': 'Malta',
  'LU': 'Luxembourg',
  'LI': 'Liechtenstein',
  'MC': 'Monaco',
  'AD': 'Andorra',
  'SM': 'San Marino',
  'VA': 'Vatican City',
  'PL': 'Poland',
  'CZ': 'Czech Republic',
  'SK': 'Slovakia',
  'HU': 'Hungary',
  'RO': 'Romania',
  'BG': 'Bulgaria',
  'HR': 'Croatia',
  'SI': 'Slovenia',
  'BA': 'Bosnia and Herzegovina',
  'RS': 'Serbia',
  'ME': 'Montenegro',
  'MK': 'North Macedonia',
  'AL': 'Albania',
  'XK': 'Kosovo',
  'EE': 'Estonia',
  'LV': 'Latvia',
  'LT': 'Lithuania',
  'BY': 'Belarus',
  'UA': 'Ukraine',
  'MD': 'Moldova',
  'RU': 'Russia',
  'KZ': 'Kazakhstan',
  'KG': 'Kyrgyzstan',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'UZ': 'Uzbekistan',
  'MN': 'Mongolia',
  'CN': 'China',
  'TW': 'Taiwan',
  'HK': 'Hong Kong',
  'MO': 'Macau',
  'JP': 'Japan',
  'KR': 'South Korea',
  'KP': 'North Korea',
  'TH': 'Thailand',
  'VN': 'Vietnam',
  'LA': 'Laos',
  'KH': 'Cambodia',
  'MY': 'Malaysia',
  'SG': 'Singapore',
  'BN': 'Brunei',
  'ID': 'Indonesia',
  'PH': 'Philippines',
  'TL': 'East Timor',
  'MM': 'Myanmar',
  'BD': 'Bangladesh',
  'BT': 'Bhutan',
  'NP': 'Nepal',
  'LK': 'Sri Lanka',
  'MV': 'Maldives',
  'IN': 'India',
  'PK': 'Pakistan',
  'AF': 'Afghanistan',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'SY': 'Syria',
  'LB': 'Lebanon',
  'JO': 'Jordan',
  'IL': 'Israel',
  'PS': 'Palestine',
  'SA': 'Saudi Arabia',
  'YE': 'Yemen',
  'OM': 'Oman',
  'AE': 'United Arab Emirates',
  'QA': 'Qatar',
  'BH': 'Bahrain',
  'KW': 'Kuwait',
  'TR': 'Turkey',
  'GE': 'Georgia',
  'AM': 'Armenia',
  'AZ': 'Azerbaijan',
  'EG': 'Egypt',
  'LY': 'Libya',
  'TN': 'Tunisia',
  'DZ': 'Algeria',
  'MA': 'Morocco',
  'SD': 'Sudan',
  'SS': 'South Sudan',
  'ET': 'Ethiopia',
  'ER': 'Eritrea',
  'DJ': 'Djibouti',
  'SO': 'Somalia',
  'KE': 'Kenya',
  'UG': 'Uganda',
  'TZ': 'Tanzania',
  'RW': 'Rwanda',
  'BI': 'Burundi',
  'MW': 'Malawi',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'BW': 'Botswana',
  'NA': 'Namibia',
  'ZA': 'South Africa',
  'LS': 'Lesotho',
  'SZ': 'Eswatini',
  'MG': 'Madagascar',
  'MU': 'Mauritius',
  'SC': 'Seychelles',
  'KM': 'Comoros',
  'YT': 'Mayotte',
  'RE': 'Réunion',
  'MZ': 'Mozambique',
  'AO': 'Angola',
  'CD': 'Democratic Republic of the Congo',
  'CG': 'Republic of the Congo',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CM': 'Cameroon',
  'GQ': 'Equatorial Guinea',
  'GA': 'Gabon',
  'ST': 'São Tomé and Príncipe',
  'GH': 'Ghana',
  'TG': 'Togo',
  'BJ': 'Benin',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'BF': 'Burkina Faso',
  'ML': 'Mali',
  'SN': 'Senegal',
  'GM': 'Gambia',
  'GW': 'Guinea-Bissau',
  'GN': 'Guinea',
  'SL': 'Sierra Leone',
  'LR': 'Liberia',
  'CI': 'Ivory Coast',
  'MR': 'Mauritania',
  'CV': 'Cape Verde',
  'BR': 'Brazil',
  'AR': 'Argentina',
  'CL': 'Chile',
  'UY': 'Uruguay',
  'PY': 'Paraguay',
  'BO': 'Bolivia',
  'PE': 'Peru',
  'EC': 'Ecuador',
  'CO': 'Colombia',
  'VE': 'Venezuela',
  'GY': 'Guyana',
  'SR': 'Suriname',
  'GF': 'French Guiana',
  'FK': 'Falkland Islands',
  'MX': 'Mexico',
  'GT': 'Guatemala',
  'BZ': 'Belize',
  'SV': 'El Salvador',
  'HN': 'Honduras',
  'NI': 'Nicaragua',
  'CR': 'Costa Rica',
  'PA': 'Panama',
  'CU': 'Cuba',
  'JM': 'Jamaica',
  'HT': 'Haiti',
  'DO': 'Dominican Republic',
  'PR': 'Puerto Rico',
  'VI': 'U.S. Virgin Islands',
  'AG': 'Antigua and Barbuda',
  'BB': 'Barbados',
  'DM': 'Dominica',
  'GD': 'Grenada',
  'KN': 'Saint Kitts and Nevis',
  'LC': 'Saint Lucia',
  'VC': 'Saint Vincent and the Grenadines',
  'TT': 'Trinidad and Tobago',
  'BS': 'Bahamas',
  'NZ': 'New Zealand',
  'FJ': 'Fiji',
  'PG': 'Papua New Guinea',
  'SB': 'Solomon Islands',
  'VU': 'Vanuatu',
  'NC': 'New Caledonia',
  'PF': 'French Polynesia',
  'WS': 'Samoa',
  'TO': 'Tonga',
  'KI': 'Kiribati',
  'TV': 'Tuvalu',
  'NR': 'Nauru',
  'PW': 'Palau',
  'FM': 'Micronesia',
  'MH': 'Marshall Islands',
  'MP': 'Northern Mariana Islands',
  'GU': 'Guam',
  'AS': 'American Samoa',
  'CK': 'Cook Islands',
  'NU': 'Niue',
  'TK': 'Tokelau',
  'WF': 'Wallis and Futuna',
  'PN': 'Pitcairn Islands',
  'SH': 'Saint Helena',
  'AC': 'Ascension Island',
  'TA': 'Tristan da Cunha',
  'GS': 'South Georgia and the South Sandwich Islands',
  'BV': 'Bouvet Island',
  'HM': 'Heard Island and McDonald Islands',
  'AQ': 'Antarctica',
  'TF': 'French Southern and Antarctic Lands',
  'IO': 'British Indian Ocean Territory',
  'CC': 'Cocos Islands',
  'CX': 'Christmas Island',
  'NF': 'Norfolk Island'
};

/**
 * Convert a language code to its full language name
 * @param {string} languageCode - The ISO 639-1 language code (e.g., 'en', 'fr')
 * @returns {string} - The full language name (e.g., 'English', 'French')
 */
export const getLanguageName = (languageCode) => {
  if (!languageCode) return 'English'; // Default fallback
  return LANGUAGE_NAMES[languageCode] || languageCode; // Return code if not found
};

/**
 * Convert a country code to its full country name
 * @param {string} countryCode - The ISO 3166-1 alpha-2 country code (e.g., 'US', 'GB')
 * @returns {string} - The full country name (e.g., 'United States', 'United Kingdom')
 */
export const getCountryName = (countryCode) => {
  if (!countryCode) return '';
  return COUNTRY_NAMES[countryCode] || countryCode; // Return code if not found
};

/**
 * Convert an array of country codes to their full country names
 * @param {string[]} countryCodes - Array of ISO 3166-1 alpha-2 country codes
 * @returns {string[]} - Array of full country names
 */
export const getCountryNames = (countryCodes) => {
  if (!countryCodes || !Array.isArray(countryCodes)) return [];
  return countryCodes.map(code => getCountryName(code));
};

const languageCountryUtils = {
  getLanguageName,
  getCountryName,
  getCountryNames
};

export default languageCountryUtils;
